name: Generate Trophies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Trophy
        uses: ryo-ma/github-profile-trophy@v1
        with:
          username: ayushcmd
          theme: gruvbox
          no-frame: true
          no-bg: true
          margin-w: 6
          column: 7
          output-path: trophy.svg

      - name: Commit Trophy SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git diff --cached --quiet || git commit -m "Update trophy stats"
          git push
